# Array Function

In [7]:
import numpy as np

In [9]:
heights=[1.6, 1.8, 1.65, 1.7]
weights=[56, 80, 71, 67]
bmi=weights/heights**2
# It doesn't work beacause they are LISTS and not ARRAYS

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [10]:
np_heights=np.array(heights)
np_weights=np.array(weights)
print("Type: ", type(np_heights))

Type:  <class 'numpy.ndarray'>


In [8]:
bmi=np_weights/np_heights**2
print(bmi)

[21.875      24.69135802 26.07897153 23.183391  ]


- **Remarks**: array is a brand new object with its charateristics

In [9]:
python_list=[1, 2, 3]
python_array=np.array([1, 2, 3])

In [12]:
print("Sum of lists: ", python_list, "+", python_list, "=", python_list+python_list)
print("Sum of arrays: ", python_array, "+", python_array, "=", python_array+python_array)

Sum of lists:  [1, 2, 3] + [1, 2, 3] = [1, 2, 3, 1, 2, 3]
Sum of arrays:  [1 2 3] + [1 2 3] = [2 4 6]


In [13]:
print("The second person has a bmi of: ", bmi[1])

The second person has a bmi of:  24.691358024691358


In [26]:
high=bmi>23
low=bmi<23
print("high: ", high)
print("low: ", low, "\n")
print("item(s) high: ", bmi[bmi>23])
print("item(s) low: ", bmi[low])

high:  [False  True  True  True]
low:  [ True False False False] 

item(s) high:  [24.69135802 26.07897153 23.183391  ]
item(s) low:  [21.875]


In [32]:
np.array([True, 5, 2]) + np.array([1, 3, False])

array([2, 8, 2])

# 2D Arrays

In [15]:
np_2d=np.array([[1.71, 1.68, 1.80, 1.75], 
                [68.0, 74.0, 85.0, 76.0]])
print(np_2d)

[[ 1.71  1.68  1.8   1.75]
 [68.   74.   85.   76.  ]]


In [16]:
print("Liz: ", np_2d[:, 1], "\n")
print("Liz's height: ", np_2d[0,1])
print("Liz's weight: ", np_2d[1,1])

Liz:  [ 1.68 74.  ] 

Liz's height:  1.68
Liz's weight:  74.0


In [17]:
print(type(np_2d), "\n")
print("The matrix's shape:\t", np_2d.shape)


<class 'numpy.ndarray'> 

The matrix's shape:	 (2, 4)


- ***Math operations***

In [18]:
np_mat=np.array([[1,2],
                [3,4],
                [5,6]])
print(np_mat, "\t has shape: ", np_mat.shape)

[[1 2]
 [3 4]
 [5 6]] 	 has shape:  (3, 2)


In [20]:
add=np_mat+np.array([10, 10])
print(add,"\tAdd a vector [10, 10] to the matrix")

[[11 12]
 [13 14]
 [15 16]] 	Add a vector [10, 10] to the matrix


In [23]:
mult_scal=np_mat*2
print(mult_scal, "\tMultiply for a scalar")

[[ 2  4]
 [ 6  8]
 [10 12]] 	Multiply for a scalar


In [32]:
mult_hor_vect1=np_mat* np.array([1.1, 2.2])
print(mult_hor_vect1, "\tMultiply for a vector: matrix", np_mat.shape, " *vector (1x2)\n")

mult_hor_vect2=np.array([1.1, 2.2])* np_mat
print(mult_hor_vect2, "\tMultiply for a vector: vector (1x2) *matrix (3x2)")

[[ 1.1  4.4]
 [ 3.3  8.8]
 [ 5.5 13.2]] 	Multiply for a vector: matrix (3, 2)  *vector (1x2)

[[ 1.1  4.4]
 [ 3.3  8.8]
 [ 5.5 13.2]] 	Multiply for a vector: vector (1x2) *matrix (3x2)


In [31]:
mult_ver_vect1=np_mat* np.array([[1.1],
                                [2.2]])
print(mult_ver_vect1, "\tMultiply for a vector: matrix", np_mat.shape, " *vector(1x2)\n")

mult_ver_vect2=np.array([1.1, 2.2])* np_mat
print(mult_ver_vect2, "\tMultiply for a vector: vector(1x2)*matrix(3x2)")

ValueError: operands could not be broadcast together with shapes (3,2) (2,1) 

In [33]:
first_col=np_mat[:, 0]
print(first_col)

[1 3 5]


In [35]:
# With this method if the new variable is modified, the new value will affect also the old 2d array

first_col[1]=4
print(first_col)
print(np_mat)

[1 4 5]
[[1 2]
 [4 4]
 [5 6]]
